### ISSUE TITLE
Resources generates a broken Go code

### ISSUE THREAD

**Issue by jpigree** [omeid/go-resources#8] opened 2017-06-15 07:43 UTC
Hi. I am new to Go and Go resources. It looks pretty good. However, I face an issue when using it.
When I try to generate code from a simple json file, resources throws an error and produce a broken Go file.

```
resources -output="resources.go" -var="Resources" resources/manifest.json                          
2017/06/15 09:37:38 template: file:3:4: executing "file" at <reader .>: error calling reader: EOF 
```
resources/manifest.json:
```
{
  "name": "agent-ping"
}
```
I did some tests and the problem was introduced on commit 1efd65f. Before this, the code generation succeeded with the same command and inputs.

**Comment by omeid** [comment] 2017-06-15 23:59
Thanks for reporting this problem, but I am not able to reproduce it. I will add some test later today and include your example.

Give the latest master another try and see how you go.

**Comment by jpigree** [comment] 2017-06-18 16:58
Hello. Strange that you can't reproduce.

I did ask a teammate to try out and he also had the bug. I pulled your latest commit (decc875 "add live package"), I still have the same issue.

The only thing I can see is that we are not using the same Go version. I am in 1.8.3 on ArchLinux.

Anyway, I managed to fix the issue with minor changes. i will open a PR linked to this issue. To my comprehension, I still can't see how the generated code can compile without the fix. But again, I am still new to Go. :)

**Comment by omeid** [comment] 2017-06-19 01:58
Thanks for the fix, merged in!

**Closed by omeid** 2017-06-19 01:58 UTC

**Comment by omeid** [comment] 2017-06-19 02:00
Sorry, so the issue was that I had go-resources installed with a different package manager --a personal tool I use to maintain packages, similar to aur ;) -- and it would would superseded the `resources` binary in `GOPATH/bin`.
